plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
theme: jekyll-theme-slate
readme_index:
  enabled: true
layout: post
title: "GitBucket 4.2 released!"
image: https://progre.github.io/sandbox/test.png
logo: https://progre.github.io/sandbox/img/test.png
social:
  name: Progre
  links:
    - https://twitter.com/progremaster
header:
  image: &image https://progre.github.io/sandbox/test.png
image: 
  path: *image
cover: https://progre.github.io/sandbox/test.png
