theme: jekyll-theme-architect
twitter:
  username: progremaster
logo: test.png
social:
  name: Progre
  links:
    - https://twitter.com/progremaster
    - https://github.com/progre
title: title
description: desc
image: test.png
author: Proger
