theme: jekyll-theme-architect
twitter:
  username: progremaster
social:
  name: Progre
  links:
    - https://twitter.com/progremaster
    - https://github.com/progre
title: title
description: desc
logo: "/img/test.png"
image: "/img/test.png"
author: 
  name: Progre
  twitter: progemaster
seo_tag:
  image:
    path: "/img/test.png"
