theme: jekyll-theme-architect
twitter:
  username: progremaster
logo: /img/test.png
social:
  name: Progre
  links:
    - https://twitter.com/progremaster
    - https://github.com/progre
title: title
description: desc
image:
  path: /img/test.png
author: Proge
seo_tag:
  image:
    path: /img/test.png
